# Patty sensitivity testing, rewriting from dev_sensitivity_analysis.ipynb to make a cleaner code 

# DI: uses conda activate NASEM_model_poetry_SALib
from SALib.sample import saltelli
from SALib.analyze import sobol
from SALib.analyze.sobol import analyze
from SALib.sample.sobol import sample
import numpy as np
import nasem_dairy as nd  

def wrapped_execute_model(
        X, 
        coeffs_sampled, 
        user_diet_in, 
        animal_input_in, 
        equation_selection_in, 
        feed_library_in, 
        default_coeff_dict=nd.coeff_dict, 
        default_mPrt_coeff_list=nd.mPrt_coeff_list,
        func=nd.nasem):
    """
    Executes the specified model function with varying sets of coefficients and fixed model inputs, 
    returning an array of model outputs for sensitivity analysis.

    Parameters
    ----------
    X : ndarray
        A 2D numpy array where each row represents a set of sampled coefficient values to be evaluated.
    coeffs_sampled : list of str
        List of coefficient names corresponding to the columns in `X`. These are the coefficients being varied in the analysis.
    user_diet_in : dict
        Dictionary containing user-defined diet inputs for the model.
    animal_input_in : dict
        Dictionary containing animal-related inputs for the model.
    equation_selection_in : dict
        Dictionary specifying which equations to use within the model.
    feed_library_in : DataFrame 
        Data structure containing feed library information required by the model.
    default_coeff_dict : dict, optional
        The default dictionary of all coefficients used by the model, with keys as coefficient names and values as their default values. Default is `nd.coeff_dict`.
    func : function, optional
        The model function to be executed. This function should accept the model inputs as arguments and return a `ModelOutput` object. Default is `nd.execute_model`.

    Returns
    -------
    outputs : ndarray
        A 1D numpy array containing the model output of interest for each set of coefficients in `X`.

    Notes
    -----
    This function is designed to work with sensitivity analysis libraries like SALib. It takes samples of coefficient values generated by such a library, applies them to the model, and collects the outputs for analysis.

    The model function (`func`) is expected to return an object with a `get_value` method, which is used to extract the specific output of interest for sensitivity analysis.

    Examples
    --------
    >>> import numpy as np
    >>> from SALib.sample import saltelli
    >>> from nasem_dairy import execute_model, coeff_dict
    >>> 
    >>> problem = {
    ...     'num_vars': 3,
    ...     'names': ['coeff1', 'coeff2', 'coeff3'],
    ...     'bounds': [[0, 1], [0, 1], [0, 1]]
    ... }
    >>> param_values = saltelli.sample(problem, 100)
    >>> coeffs_sampled = problem['names']
    >>> 
    >>> outputs = wrapped_execute_model(param_values, coeffs_sampled, user_diet, animal_input, equation_selection, feed_library)
    """
    
    # Initialize an empty array to hold the outputs of interest for sensitivity analysis
    outputs = np.zeros(X.shape[0])

    # Iterate over each set of parameters in X
    for i, param_set in enumerate(X):
        # print(i)
        # Start with a copy of the default_coeff_dict
        updated_coeff_dict = default_coeff_dict.copy()
        updated_MPrt_coeff_list = default_mPrt_coeff_list.copy()

       #Taking the first part of the mPrt dictionary where my coefficients needed are 
        mPrt_Coeff_dict= updated_MPrt_coeff_list[0]

        # Update only the coefficients that are being modified in this analysis
        for name, value in zip(coeffs_sampled, param_set): #original
            # print(name + str(value))
            # updated_coeff_dict[name] = value #original

            if name in updated_coeff_dict:
                updated_coeff_dict[name]=value
            
            elif name in mPrt_Coeff_dict:
                mPrt_Coeff_dict[name]=value
        


        # Execute the model with the updated set of coefficients
        model_output = func(
            user_diet=user_diet_in,
            animal_input=animal_input_in,
            equation_selection=equation_selection_in,
            feed_library =feed_library_in,
            coeff_dict =updated_coeff_dict,
            mPrt_coeff_list = [mPrt_coeff_dict],
        )

        # Extract the output of interest from the ModelOutput object
        # Here, 'output_name' should be replaced with the actual name of the output you're interested in
        # output_value = model_output.get_value('Mlk_Prod_comp')
        # output_value = model_output.get_value('An_MEavail_Milk')
        # output_value = model_output.get_value('Mlk_Prod_NEalow')
        output_value =  model_output.get_value('Trg_Mlk_MEout')
        # output_value2 = model_output.get_value('Mlk_Fatemp_g')
        
        # Store the extracted output in the outputs array
        outputs[i] = output_value
        print(f"Output for sample {i}: {output_value}")  # Debug print

    return outputs


import importlib_resources
import pandas as pd
import os 
path_to_package_data = importlib_resources.files("nasem_dairy.data")
path = os.path.join(os.getcwd(), "dev/data")

# Read_csv to load required data into env
#user_diet_in, animal_input_in, equation_selection_in = nd.read_csv_input(path_to_package_data.joinpath("./input.csv"))

#Reading in PK inputs
user_diet_in, animal_input_in, equation_selection_in, _ = nd.read_csv_input(f"{path}/input.pk.csv")

# Load feed library
#feed_library_in = pd.read_csv(path_to_package_data.joinpath("NASEM_feed_library.csv"))


#Loading PK feed library
feed_library_in = pd.read_csv(f"{path}/NASEM_feed_library.pk.csv") 

# trying to run with mprt coefficients and coeff dict, this one works!! 

# import pandas as pd

# # --- Define parameters and their test ranges ---
# param_values = {
#     "Maintenance": [0.1, 0.2, 0.05],
#     "Lact_Efficiency": [0.66, 1.32, 0.33],
#     "Kl_ME_NE": [0.66, 1.32, 0.33],
#     "Frame_Gain_Cow": [0.4, 0.8, 0.2],
#     "Kr_ME_RE_Gain": [0.75, 1.5, 0.3],
#     "Kr_ME_RE_Loss": [0.89, 1.8, 0.4],
#     "Rum_dcNDF_Var1": [-31.9, -60, 0.1],
#     "Rum_dcNDF_Var2":	[0.721, 1.4, 0.35],
# "Rum_dcNDF_Var3":	[0.247, 0.01, 1],
# "Rum_dcNDF_Var4":	[6.63, 12, 3],
# "Rum_dcNDF_Var5":	[0.211, 0.4, 0.1],
# "Rum_dcNDF_Var6": 	[0.387, 1, 0.15],
# "Rum_dcNDF_Var7":	[0.121, 0.2, 0.05],
# "Rum_dcNDF_Var8": 	[1.51, 3, 0.75],
# "Rum_dcSt_Var1":	[70.6, 140, 35],
# "Rum_dcSt_Var2":	[1.45, 3, 0.9],
# "Rum_dcSt_Var3":	[0.424, 0.8, 0.2],
# "Rum_dcSt_Var4":	[1.39, 3, 0.5],
# "Rum_dcSt_Var5":	[0.0219, 0.05, 1],
# "Rum_dcSt_Var6":	[0.154, 0.5, 0.05],
# "KpFor":	[4.87, 9, 2],
# "KpConc":	[5.28, 12, 2.5],
# "IntRUP":	[-0.086, 1, -2],
# "KmMiNRDNDF":	[0.0939, 1.8, 0.45],
# "KmMiNRDSt":	[0.0274, 0.5, 0.01],
# "VmMiNInt":	[100.8, 200, 50],
# "VmMiNRDPSlp":	[81.56, 165, 40],
# "Du_EndCP_g_Var1":	[96.1, 200, 45],
# "Du_EndCP_g_Var2":	[7.54, 15, 3],
# "Fe_rOMend_DMI":	[3.43, 7, 1.5],
# "TT_dcFdNDF_Lg_Var1":	[0.75, 1.5, 0.3],
# "TT_dcFdNDF_Lg_Var2":	[0.667, 1.3, 0.3],
# "TT_dcFdNDF_48h_Var1":	[12, 24, 6],
# "TT_dcFdNDF_48h_Var2":	[0.61, 1.2, 0.3],
# "TT_dcNDF_Var1":	[1.1, 2.5, 0.6],
# "TT_dcNDF_Var2":	[0.035, 0.7, 0.15],
# "TT_dcNDF_Var3":	[0.59, 1.2, 0.2],
# "TT_dcNDF_Var4":	[0.26, 0.6, 0.05],
# "Fe_Cpend_g_Var1":	[12, 24, 6],
# "Fe_Cpend_g_Var2":	[0.12, 0.24, 0.6],
# "mPrt_Int":	[-97, -180, 20],
# "mPrt_k_Ile": 	[0.885, 1.8, 0.4],
# "mPrt_k_His":	[1.675, 4, 0.8],
# "mPrt_k_Leu":  	[0.466, 1, 0.2],
# "mPrt_k_Lys":	[1.153, 3, 0.5],
# "mPrt_k_Met":	[1.84, 3, 0.8],
# "mPrt_k_OthAA":	[0.0773, 1, 0.035],
# "mPrt_k_EAA2_coeff":	[-0.00215, 1, -0.5],
# "mPrt_k_DEInp":	[10.79, 21, 5],
# "mPrt_k_DigNDF":	[-4.595, -9, -2],
# "mPrt_k_BW":	[-0.42, -0.9, -0.2],
# "Mlk_NP_g_Var1":	[17.06, 35, 7],
# "Mlk_NP_g_Var2":	[612, 1200, 300],
# "K_305RHA_MlkTP":	[1, 2, 0.5],
# "Mlk_Fatemp_g_Var1":	[453, 900, 200],
# "Mlk_Fatemp_g_Var2":	[1.42, 3, 0.7],
# "Mlk_Fatemp_g_Var3":	[24.52, 50, 12],
# "Mlk_Fatemp_g_Var4":	[0.41, 1, 0.2],
# "Mlk_Fatemp_g_Var5":	[1.8, 4, 0.9],
# "Mlk_Fatemp_g_Var6":	[1.45, 3, 0.5],
# "Mlk_Fatemp_g_Var7":	[1.34, 4, 0.5],
# "Mlk_Prod_comp_Var1":	[4.541, 9, 2],
# "Mlk_Prod_comp_Var2":	[11.13, 22, 5],
# "Mlk_Prod_comp_Var3":	[2.65, 5, 1.2],
# "Mlk_Prod_comp_Var4":	[0.1829, 1, 0.09],
# "Mlk_Prod_comp_Var5":	[0.06257, 1.2, 0.03],
# "Mlk_Prod_comp_Var6":	[2.766*10**-4, 1, 0.5],
# "Mlk_Prod_comp_Var7":	[1.603*10**-6, 1, 2],
# "Mlk_Prod_comp_Var8":	[7.397*10**-9, 1, 2],
# "Mlk_Prod_comp_Var9":	[1.567, 4, 0.75],
# "Scrf_CP_g_Var1":	[0.2, 0.4, 0.05],
# "Ur_Nend_Urea_g_Var1":	[0.01, 0.02, 0.005],
# "Ur_Nend_Creatn_g_Var1":	[0.00946, 0.1, 0.0005],
# "Ur_Nend_PD_g_Var1":	[0.0271, 0.05, 0.005],
# "fN_3MH": [(3*14)/169, 0.05, 2],
# "Ur_NPend_3MH_g_Var1":	[7.82, 16, 3],
# "Ur_NPend_3MH_g_Var2":	[0.55, 1.5, 0.25],
# "Ur_Nend_g_Var1":	[0.053, 1, 0.025],
# "Km_MP_NP_Trg":	[0.69, 1.3, 0.3],
# "Kx_MP_NP_Trg":	[0.69, 1.3, 0.3],
# "An_GasEOut_Lact_Var1":	[0.294, 0.6, 0.05],
# "An_GasEOut_Lact_Var2":	[0.347, 0.7, 0.15],
# "An_GasEOut_Lact_Var3":	[0.0409, 0.08, 0.02],
# }

# # --- Output keys ---
# output_keys = [
#     "Mlk_NP_g",
#     "Mlk_Fat_g",
#     "Mlk_Prod",
#     "Ur_Nout_CPcatab",
#     "An_MEavail_Grw",
#     "An_NEm_ME",
#     "An_REgain",
#     "An_MEuse",
#     "An_NELuse",
#     "An_MEbal",
#     "An_NEuse",
#     "An_NEbal",
#     "Body_Gain_NEalow"
# ]

# # --- Baseline coefficient copies ---
# base_coeff = nd.coeff_dict.copy()
# mPrt_coeff_copy = nd.mPrt_coeff_list[0].copy()  # baseline mPrt coefficients

# # --- Store results ---
# results_list = []

# # --- One-at-a-time loop ---
# for param, values in param_values.items():
#     for v in values:
#         # Copy dictionaries for this iteration
#         coeff_copy = base_coeff.copy()
#         mPrt_copy = mPrt_coeff_copy.copy()

#         # Update correct dictionary
#         if param in coeff_copy:
#             coeff_copy[param] = v
#         elif param in mPrt_copy:
#             mPrt_copy[param] = v
#         else:
#             print(f"⚠️ Parameter {param} not found in either dictionary")

#         # Run model
#         output = nd.nasem(
#             user_diet=user_diet_in,
#             animal_input=animal_input_in,
#             equation_selection=equation_selection_in,
#             feed_library=feed_library_in,
#             coeff_dict=coeff_copy,
#             mPrt_coeff_list=[mPrt_copy]
#         )

#         # Collect outputs
#         result = {key: output.get_value(key) for key in output_keys}
#         result["Parameter"] = param
#         result["Value"] = v
#         results_list.append(result)

# # --- Combine results ---
# df = pd.DataFrame(results_list)
# df = df[["Parameter", "Value", *output_keys]]

# # --- Baseline output for comparison ---
# baseline_output = nd.nasem(
#     user_diet=user_diet_in,
#     animal_input=animal_input_in,
#     equation_selection=equation_selection_in,
#     feed_library=feed_library_in,
#     coeff_dict=nd.coeff_dict,
#     mPrt_coeff_list=[mPrt_coeff_copy]
# )
# baseline_values = {key: baseline_output.get_value(key) for key in output_keys}

# # --- Compute change and percent change ---
# for key in output_keys:
#     df[f"{key}_change"] = df[key] - baseline_values[key]
#     df[f"{key}_pct_change"] = (
#         (df[key] - baseline_values[key]) / baseline_values[key] * 100
#         if baseline_values[key] not in (None, 0) else None
#     )

# # --- Identify which parameters affected outputs ---
# changed_flags = (df[[f"{k}_change" for k in output_keys]] != 0).any(axis=1)
# df["AnyChange"] = changed_flags

# # --- Create summary: which outputs each parameter affected ---
# summary = (
#     df.groupby("Parameter")[[f"{k}_change" for k in output_keys]]
#     .apply(lambda x: (x != 0).any())
#     .rename(columns={f"{k}_change": k for k in output_keys})
# )

# # --- Display results ---
# print(df)
# print("\n📊 Parameters that affected each output:")
# print(summary)
# print("\n✅ 'True' means that changing that parameter altered the given output")

# # --- Save results ---
# df.to_csv("nasem_OAT_results_with_mPrt.csv", index=False)
# summary.to_csv("nasem_OAT_summary_with_mPrt.csv")

# ---------------------------
# Sobol Sensitivity Analysis (one output at a time)
# ---------------------------

import pandas as pd
import numpy as np
from SALib.sample.sobol import sample as sobol_sample
from SALib.analyze.sobol import analyze as sobol_analyze
import matplotlib.pyplot as plt
import gc
import os

# You need nd, user_diet_in, animal_input_in, equation_selection_in, feed_library_in
# already defined in your environment, just like in your original script.

# ---------------------------
# 0. OPTIONS
# ---------------------------

# You can safely go > 2000 now. 2048 is a nice value for Sobol sequences.
N = 2048
calc_second_order = False      # Set True only if you really need S2 (much heavier)

# Choose which output to analyze in THIS run:
# Must be one of the output_keys defined below.
target_output = "An_NEm_ME"    # <- change this each time you run the script

# ---- SAVE RESULTS IN dev/notebooks/sobol_results_single ----
PROJECT_ROOT = os.getcwd()
BASE_PATH = os.path.join(PROJECT_ROOT, "dev/notebooks")
OUTDIR = os.path.join(BASE_PATH, "sobol_results_single")
os.makedirs(OUTDIR, exist_ok=True)

print("Saving Sobol results to:", OUTDIR)
# ---------------------------
# 1. PARAMETER SETUP
# ---------------------------

param_values = {
    "Maintenance": [0.05, 0.2],
    "Lact_Efficiency": [0.33, 1.32],
    "Kl_ME_NE": [0.33, 1.32],
    "Frame_Gain_Cow": [0.2, 0.8],
    # "Rum_dcNDF_Var1": [-63.8, -15.95],
    # "Rum_dcNDF_Var2": [0.3605, 1.442],
    # "Rum_dcNDF_Var3": [0.1235, 0.494],
    # "Rum_dcNDF_Var4": [3.315, 13.26],
    # "Rum_dcNDF_Var5": [0.1055, 0.422],
    # "Rum_dcNDF_Var6": [0.1935, 0.774],
    # "Rum_dcNDF_Var7": [0.0605, 0.242],
    # "Rum_dcNDF_Var8": [0.755, 3.02],
    # "Rum_dcSt_Var1": [35.3, 141.2],
    # "Rum_dcSt_Var2": [0.725, 2.9],
    # "Rum_dcSt_Var3": [0.212, 0.848],
    # "Rum_dcSt_Var4": [0.695, 2.78],
    # "Rum_dcSt_Var5": [0.01095, 0.0438],
    # "Rum_dcSt_Var6": [0.077, 0.308],
    # "KpFor": [2.435, 9.74],
    # "KpConc": [2.64, 10.56],
    # "IntRUP": [-0.172, -0.043],
    # "KmMiNRDNDF": [0.04695, 0.1878],
    # "KmMiNRDSt": [0.0137, 0.0548],
    # "VmMiNInt": [50.4, 201.6],
    # "VmMiNRDPSlp": [40.78, 163.12],
    # "Fe_rOMend_DMI": [1.715, 6.86],
    # "TT_dcFdNDF_Lg_Var1": [0.375, 1.5],
    # "TT_dcFdNDF_Lg_Var2": [0.3335, 1.334],
    # "TT_dcNDF_Var1": [0.55, 2.2],
    # "TT_dcNDF_Var2": [0.0175, 0.07],
    # "TT_dcNDF_Var3": [0.295, 1.18],
    # "TT_dcNDF_Var4": [0.13, 0.52],
    # "Fe_Cpend_g_Var1": [6, 24],
    # "Fe_Cpend_g_Var2": [0.06, 0.24],
    # "mPrt_Int": [-194, -48.5],
    # "mPrt_k_Ile": [0.4425, 1.77],
    # "mPrt_k_His": [0.8375, 3.35],
    # "mPrt_k_Leu": [0.233, 0.932],
    # "mPrt_k_Lys": [0.5765, 2.306],
    # "mPrt_k_Met": [0.92, 3.68],
    # "mPrt_k_OthAA": [0.03865, 0.1546],
    # "mPrt_k_EAA2_coeff": [-0.0043, -0.001075],
    # "mPrt_k_DEInp": [5.395, 21.58],
    # "mPrt_k_DigNDF": [-9.19, -2.2975],
    # "mPrt_k_BW": [-0.84, -0.21],
    # "Mlk_NP_g_Var1": [8.53, 34.12],
    # "Mlk_NP_g_Var2": [306, 1224],
    # "Mlk_Fatemp_g_Var1": [226.5, 906],
    # "Mlk_Fatemp_g_Var2": [0.71, 2.84],
    # "Mlk_Fatemp_g_Var3": [12.26, 49.04],
    # "Mlk_Fatemp_g_Var4": [0.205, 0.82],
    # "Mlk_Fatemp_g_Var5": [0.9, 3.6],
    # "Mlk_Fatemp_g_Var6": [0.725, 2.9],
    # "Mlk_Fatemp_g_Var7": [0.67, 2.68],
    # "Mlk_Prod_comp_Var1": [2.2705, 9.082],
    # "Mlk_Prod_comp_Var2": [5.565, 22.26],
    # "Mlk_Prod_comp_Var3": [1.325, 5.3],
    # "Mlk_Prod_comp_Var4": [0.09145, 0.3658],
    # "Mlk_Prod_comp_Var5": [0.031285, 0.12514],
    # "Mlk_Prod_comp_Var6": [1.383*10**-4, 5.532*10**-4],
    # "Mlk_Prod_comp_Var7": [8.015*10**-7, 3.206*10**-6],
    # "Mlk_Prod_comp_Var8": [3.6985*10**-9, 1.4794*10**-8],
    # "Scrf_CP_g_Var1": [0.1, 0.4],
    # "Ur_Nend_g_Var1": [0.0265, 0.106],
    # "An_GasEOut_Lact_Var1": [0.147, 0.588],
    # "An_GasEOut_Lact_Var2": [0.1735, 0.694],
    # "An_GasEOut_Lact_Var3": [0.02045, 0.0818],
}

output_keys = [
    "Mlk_NP_g",
    "Mlk_Fat_g",
    "Mlk_Prod",
    "Ur_Nout_CPcatab",
    "An_MEavail_Grw",
    "An_NEm_ME",
    "An_MEuse",
    "An_NELuse",
    "An_MEbal",
    "An_NEuse",
    "An_NEbal",
    "Body_Gain_NEalow"
]

if target_output not in output_keys:
    raise ValueError(f"target_output='{target_output}' not in output_keys: {output_keys}")

target_index = output_keys.index(target_output)

param_names = list(param_values.keys())
bounds = [[v[0], v[1]] for v in param_values.values()]

problem = {
    "num_vars": len(param_names),
    "names": param_names,
    "bounds": bounds,
}

print(f"Total parameters: {len(param_names)}")
print(f"Analyzing output: {target_output} (index {target_index})")
print(f"N base sample size: {N}, second-order: {calc_second_order}")

# ---------------------------
# 2. GENERATE SOBOL SAMPLES
# ---------------------------

print("Generating Sobol samples...")
X = sobol_sample(problem, N, calc_second_order=calc_second_order)
print(f"Sample matrix shape: {X.shape}")

# ---------------------------
# 3. MODEL WRAPPER
# ---------------------------

def run_model(X_row):
    # Copies from nasem_dairy or your nd module
    coeff_copy = nd.coeff_dict.copy()
    mPrt_copy = nd.mPrt_coeff_list[0].copy()

    # Assign sample values to correct dict
    for i, name in enumerate(param_names):
        val = X_row[i]
        if name in coeff_copy:
            coeff_copy[name] = val
        elif name in mPrt_copy:
            mPrt_copy[name] = val

    # Run your model (same as before)
    out = nd.nasem(
        user_diet=user_diet_in,
        animal_input=animal_input_in,
        equation_selection=equation_selection_in,
        feed_library=feed_library_in,
        coeff_dict=coeff_copy,
        mPrt_coeff_list=[mPrt_copy]
    )

    # Return list of all outputs (same order as output_keys)
    return [out.get_value(k) for k in output_keys]


# ---------------------------
# 4. RUN MODEL FOR ALL SAMPLES (one output stored)
# ---------------------------

print("Running model for all Sobol samples...")
n_samples = X.shape[0]
Y = np.zeros(n_samples)

for i in range(n_samples):
    if (i + 1) % 500 == 0 or i == 0:
        print(f"  Processing sample {i + 1}/{n_samples}")
    row = X[i, :]
    out_values = run_model(row)          # list of 12 outputs
    Y[i] = out_values[target_index]      # store only the target output

print(f"Collected Y for {target_output}: shape {Y.shape}")

# ---------------------------
# 5. SOBOL ANALYSIS
# ---------------------------

print("Running Sobol analysis...")
Si = sobol_analyze(
    problem,
    Y,
    calc_second_order=calc_second_order,
    print_to_console=False
)

# ---------------------------
# 6. SAVE RESULTS
# ---------------------------

# S1 + ST table
df_S1_ST = pd.DataFrame({
    "Parameter": param_names,
    "Output": target_output,
    "S1": Si["S1"],
    "S1_conf": Si["S1_conf"],
    "ST": Si["ST"],
    "ST_conf": Si["ST_conf"],
})

csv_path = os.path.join(OUTDIR, f"sobol_{target_output}_S1_ST.csv")
df_S1_ST.to_csv(csv_path, index=False)
print(f"S1/ST saved to: {csv_path}")

# Optional: S2 save if enabled
if calc_second_order and "S2" in Si:
    S2 = Si["S2"]
    S2_conf = Si["S2_conf"]
    df_S2 = []
    for i, name_i in enumerate(param_names):
        for j, name_j in enumerate(param_names):
            if j <= i:
                continue
            df_S2.append({
                "Output": target_output,
                "Param_A": name_i,
                "Param_B": name_j,
                "S2": S2[i, j],
                "S2_conf": S2_conf[i, j],
            })
    df_S2 = pd.DataFrame(df_S2)
    s2_path = os.path.join(OUTDIR, f"sobol_{target_output}_S2.csv")
    df_S2.to_csv(s2_path, index=False)
    print(f"S2 saved to: {s2_path}")

# ---------------------------
# 7. SIMPLE BAR PLOT (S1 + ST)
# ---------------------------

plt.figure(figsize=(10, 6))
df_plot = df_S1_ST.sort_values("ST", ascending=False)

x = np.arange(len(df_plot))
width = 0.35

plt.bar(x - width / 2, df_plot["S1"], width, label="S1 (First-order)")
plt.bar(x + width / 2, df_plot["ST"], width, label="ST (Total-order)")
plt.xticks(x, df_plot["Parameter"], rotation=90)
plt.ylabel("Sobol index")
plt.title(f"Sobol S1 & ST for {target_output} (N={N})")
plt.legend()
plt.tight_layout()

plot_path = os.path.join(OUTDIR, f"Sobol_S1_ST_{target_output}.png")
plt.savefig(plot_path, dpi=300)
plt.close()
print(f"Plot saved to: {plot_path}")

# ---------------------------
# 8. CLEAN UP
# ---------------------------

del X, Y, Si, df_S1_ST
gc.collect()

print("\n🎉 Sobol analysis complete for", target_output)