project:
  type: website
  output-dir: _site

# execute:
#   freeze: false

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

website:
  title: "docs"
  page-navigation: true
  navbar:
    # background: light
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Reference"
        file: reference/index.qmd


quartodoc:
  # the name used to import the package you want to create reference docs for
  package: nasem_dairy
  rewrite_all_pages: true
  renderer:
    style: markdown
    # display_name: relative

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: NASEM_equations
      desc: Functions that contain only equations from the Nutrient Requirements of Dairy Cattle model.
   
    - subtitle: Energy of Maintenance
      desc: ""
      package: nasem_dairy.NASEM_equations.energy_requirement_equations
      contents:
        - calculate_An_NEmUse_NS
        - calculate_An_NEm_Act_Graze
        - calculate_An_NEm_Act_Parlor 
        - calculate_An_NEm_Act_Topo 
        - calculate_An_NEmUse_Act 
        - calculate_An_NEmUse
        - calculate_An_MEmUse 
    
    - subtitle: Energy of Gain
      desc: ""
      package: nasem_dairy.NASEM_equations.energy_requirement_equations
      contents:
        - calculate_Rsrv_NEgain 
        - calculate_Kr_ME_RE
        - calculate_Rsrv_MEgain
        - calculate_Frm_NEgain
        - calculate_Frm_MEgain
        - calculate_An_MEgain
    
    - subtitle: Energy of Gestation
      desc: ""
      package: nasem_dairy.NASEM_equations.energy_requirement_equations
      contents:
        - calculate_Gest_REgain
        - calculate_Gest_MEuse

    - subtitle: Energy of Milk
      desc: ""
      package: nasem_dairy.NASEM_equations.energy_requirement_equations
      contents:
        - calculate_Trg_Mlk_NEout
        - calculate_Trg_Mlk_MEout
        - calculate_Trg_MEuse

    - subtitle: Temp - milk equations
      desc: ""
      package: nasem_dairy.NASEM_equations.milk_equations
      contents:
        - calculate_Trg_NEmilk_Milk
      
    - subtitle: Temp - body comp
      desc: ""
      package: nasem_dairy.NASEM_equations.body_composition_equations
      contents:
        - calculate_Frm_Fatgain
        - calculate_Frm_CPgain
        - calculate_Rsrv_Fatgain
        - calculate_Rsrv_CPgain
      
    - subtitle: Temp - gestation eqns
      desc: ""
      package: nasem_dairy.NASEM_equations.gestation_equations
      contents:
        - calculate_GrUter_BWgain

    - subtitle: DMI equations
      desc: ALL DMI equations
      package: nasem_dairy.NASEM_equations.DMI_equations
      contents:
        - calculate_Kb_LateGest_DMIn
        - calculate_An_PrePartWklim
        - calculate_Dt_DMIn_Heif_LateGestInd
        - calculate_Dt_DMIn_Heif_LateGestPen
        - calculate_Dt_NDFdev_DMI
        - calculate_Dt_DMIn_Heif_NRCa
        - calculate_Dt_DMIn_Heif_NRCad
        - calculate_Dt_DMIn_Heif_H1
        - calculate_Dt_DMIn_Heif_H2
        - calculate_Dt_DMIn_Heif_HJ1
        - calculate_Dt_DMIn_Heif_HJ2
        - calculate_Dt_DMIn_Lact1
        - calculate_Dt_DMIn_BW_LateGest_i
        - calculate_Dt_DMIn_BW_LateGest_p
        - calculate_Dt_DMIn_DryCow1_FarOff
        - calculate_Dt_DMIn_DryCow1_Close
        - calculate_Dt_DMIn_DryCow2

    - title: DMI eq - with module doc
      package: nasem_dairy.NASEM_equations
      contents: 
       - DMI_equations


    - title: Utilility functions
      desc: Functions to execute equations from NASEM_equations 
      
    - subtitle: Model Execution
      desc: Functions related to importing data, user selections and model execution. Does not include any model equations.
      package: nasem_dairy.ration_balancer.ration_balancer_functions
      contents:
        - check_coeffs_in_coeff_dict
        - get_feed_rows_feedlibrary
        - read_csv_input
        - read_infusion_input
    - subtitle: "Advanced: Default Values"
      package: nasem_dairy.ration_balancer
      contents:
        - default_values_dictionaries

    - subtitle: "Model Output"
      package: nasem_dairy.ration_balancer.ModelOutput
      contents:
        - ModelOutput


        #  the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
      #  - ration_balancer_functions
      #  - name: ration_balancer_functions
      #     children: embedded


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true


filters:
  - interlinks

interlinks:
  sources: {}


