# Function reference {.doc .doc-index}

## NASEM_equations

Functions that contain only equations from the Nutrient Requirements of Dairy Cattle model.

### DMI equations

ALL DMI equations

| | |
| --- | --- |
| [calculate_Kb_LateGest_DMIn](calculate_Kb_LateGest_DMIn.qmd#nasem_dairy.NASEM_equations.dev_DMI_equations.calculate_Kb_LateGest_DMIn) | Calculate the ______________ for predicting dry matter intake (DMI) in late gestation for heifers. |
| [calculate_An_PrePartWklim](calculate_An_PrePartWklim.qmd#nasem_dairy.NASEM_equations.dev_DMI_equations.calculate_An_PrePartWklim) |  |
| [calculate_Dt_DMIn_Heif_LateGestInd](calculate_Dt_DMIn_Heif_LateGestInd.qmd#nasem_dairy.NASEM_equations.dev_DMI_equations.calculate_Dt_DMIn_Heif_LateGestInd) |  |
| [calculate_Dt_DMIn_Heif_LateGestPen](calculate_Dt_DMIn_Heif_LateGestPen.qmd#nasem_dairy.NASEM_equations.dev_DMI_equations.calculate_Dt_DMIn_Heif_LateGestPen) |  |
| [calculate_Dt_NDFdev_DMI](calculate_Dt_NDFdev_DMI.qmd#nasem_dairy.NASEM_equations.dev_DMI_equations.calculate_Dt_NDFdev_DMI) |  |
| [calculate_Dt_DMIn_Heif_NRCa](calculate_Dt_DMIn_Heif_NRCa.qmd#nasem_dairy.NASEM_equations.dev_DMI_equations.calculate_Dt_DMIn_Heif_NRCa) | Test docs for calcualte_Dt_DMIn_Heif_NRCa |
| [calculate_Dt_DMIn_Heif_NRCad](calculate_Dt_DMIn_Heif_NRCad.qmd#nasem_dairy.NASEM_equations.dev_DMI_equations.calculate_Dt_DMIn_Heif_NRCad) |  |
| [calculate_Dt_DMIn_Heif_H1](calculate_Dt_DMIn_Heif_H1.qmd#nasem_dairy.NASEM_equations.dev_DMI_equations.calculate_Dt_DMIn_Heif_H1) |  |
| [calculate_Dt_DMIn_Heif_H2](calculate_Dt_DMIn_Heif_H2.qmd#nasem_dairy.NASEM_equations.dev_DMI_equations.calculate_Dt_DMIn_Heif_H2) |  |
| [calculate_Dt_DMIn_Heif_HJ1](calculate_Dt_DMIn_Heif_HJ1.qmd#nasem_dairy.NASEM_equations.dev_DMI_equations.calculate_Dt_DMIn_Heif_HJ1) | _summary_ |
| [calculate_Dt_DMIn_Heif_HJ2](calculate_Dt_DMIn_Heif_HJ2.qmd#nasem_dairy.NASEM_equations.dev_DMI_equations.calculate_Dt_DMIn_Heif_HJ2) | Calculate the predicted dry matter intake (DMI) for Holstein x Jersey crossbred heifers |
| [calculate_Dt_DMIn_Lact1](calculate_Dt_DMIn_Lact1.qmd#nasem_dairy.NASEM_equations.dev_DMI_equations.calculate_Dt_DMIn_Lact1) | Calculate the predicted dry matter intake (DMI) for lactating dairy cows using equation 8. |
| [calculate_Dt_DMIn_BW_LateGest_i](calculate_Dt_DMIn_BW_LateGest_i.qmd#nasem_dairy.NASEM_equations.dev_DMI_equations.calculate_Dt_DMIn_BW_LateGest_i) |  |
| [calculate_Dt_DMIn_BW_LateGest_p](calculate_Dt_DMIn_BW_LateGest_p.qmd#nasem_dairy.NASEM_equations.dev_DMI_equations.calculate_Dt_DMIn_BW_LateGest_p) |  |
| [calculate_Dt_DMIn_DryCow1_FarOff](calculate_Dt_DMIn_DryCow1_FarOff.qmd#nasem_dairy.NASEM_equations.dev_DMI_equations.calculate_Dt_DMIn_DryCow1_FarOff) |  |
| [calculate_Dt_DMIn_DryCow1_Close](calculate_Dt_DMIn_DryCow1_Close.qmd#nasem_dairy.NASEM_equations.dev_DMI_equations.calculate_Dt_DMIn_DryCow1_Close) |  |
| [calculate_Dt_DMIn_DryCow2](calculate_Dt_DMIn_DryCow2.qmd#nasem_dairy.NASEM_equations.dev_DMI_equations.calculate_Dt_DMIn_DryCow2) |  |