name: Main Branch CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Miniforge
      if: runner.os != 'Windows'
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: "latest"
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge

    - name: Create and Activate Conda Environment (Linux)
      if: runner.os == 'Linux'
      run: |
        conda init bash
        source ~/.bashrc
        conda create --name nasem_env python=${{ matrix.python-version }} -y
        echo "Conda environment created"
        conda activate nasem_env
        conda install -c conda-forge graph-tool -y

    - name: Initialize Conda and Create Environment (MacOS)
      if: runner.os == 'macOS'
      run: |
        conda init bash
        source ~/.bash_profile 
        conda create --name nasem_env python=${{ matrix.python-version }} -y
        conda activate nasem_env
        conda install -c conda-forge graph-tool -y

    - name: Install Poetry
      if: runner.os != 'Windows'
      run: |
        conda run -n nasem_env curl -sSL https://install.python-poetry.org | python3 -
        echo "Poetry installed"

    - name: Install Dependencies using Poetry
      if: runner.os != 'Windows'
      run: |
        conda run -n nasem_env poetry install
        echo "Dependencies installed"

    - name: Print Debug Information
      if: runner.os != 'Windows'
      run: |
        echo "Conda Environment Info:"
        conda info --envs
        echo "Active Conda Environment:"
        conda env list | grep "*"  # Shows the currently active conda environment
        echo "Installed Packages in nasem_env:"
        conda list -n nasem_env  # Lists packages installed in nasem_env
        echo "Python Version in nasem_env:"
        conda run -n nasem_env python --version  # Shows the Python version in nasem_env
        echo "Installed Packages in Poetry Environment:"
        conda run -n nasem_env poetry show
        echo "Environment Variables:"
        env

    - name: Run Tests
      if: runner.os != 'Windows'
      run: |
        conda run -n nasem_env pytest --cov=nasem_dairy --cov-report=xml --cov-report=term-missing
        echo "Tests run successfully"
  
    - name: Report Coverage to Coveralls
      if: runner.os != 'Windows'
      run: |
        conda run -n nasem_env pip install coveralls
        conda run -n nasem_env coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    - name: Install Poetry on Windows
      if: runner.os == 'Windows'
      run: |
        (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
  
    - name: Install Dependencies and Run Tests on Windows
      if: runner.os == 'Windows'
      run: |
        C:/Users/runneradmin/AppData/Roaming/Python/Scripts/poetry install
        pytest --cov=nasem_dairy --cov-report=xml --cov-report=term-missing
        pip install coveralls
        coveralls
      env:
        POETRY_VIRTUALENVS_CREATE: false
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      