name: Main Branch CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry on Linux and macOS
      if: runner.os != 'Windows'
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install Poetry on Windows
      if: runner.os == 'Windows'
      run: |
        (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -

    - name: Install dependencies on Linux and macOS
      if: runner.os != 'Windows'
      run: |
        poetry install
        poetry add importlib_resources
        conda install -c conda-forge graph-tool
      env:
        POETRY_VIRTUALENVS_CREATE: false

    - name: Install dependencies on Windows
      if: runner.os == 'Windows'
      run: |
          C:/Users/runneradmin/AppData/Roaming/Python/Scripts/poetry install
          C:/Users/runneradmin/AppData/Roaming/Python/Scripts/poetry add importlib_resources
      env:
          POETRY_VIRTUALENVS_CREATE: false

    - name: Run tests with coverage
      run: |
        pytest --cov=nasem_dairy --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Coveralls
      run: |
        pip install coveralls
        coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}