name: Run Pytest

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry on Linux and macOS
      if: runner.os != 'Windows'
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install Poetry on Windows
      if: runner.os == 'Windows'
      run: |
        (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -

    - name: Install dependencies
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          C:/Users/runneradmin/AppData/Roaming/Python/Scripts/poetry install
          C:/Users/runneradmin/AppData/Roaming/Python/Scripts/poetry add importlib_resources
        else
          poetry install
          poetry add importlib_resources
        fi
      env:
        POETRY_VIRTUALENVS_CREATE: false

    - name: Run tests
      run: |
        pytest
