name: Run Pytest

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry on Linux and macOS
      if: runner.os != 'Windows'
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install Poetry on Windows
      if: runner.os == 'Windows'
      run: |
        (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -

    - name: Add Poetry to PATH on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $env:Path += ";$env:USERPROFILE\.poetry\bin"
        [System.Environment]::SetEnvironmentVariable("PATH", $env:Path, [System.EnvironmentVariableTarget]::Process)
        echo "Updated PATH: $env:Path"

    - name: Install dependencies
      run: |
        poetry install
        poetry add importlib_resources
      env:
        POETRY_VIRTUALENVS_CREATE: false

    - name: Run tests
      run: |
        pytest
